name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      # Install dependencies
      - name: Install dependencies
        run: uv sync --frozen --all-extras

      # Format code with ruff
      - name: Format with ruff
        run: uv run ruff format --diff

      # Lint code with ruff
      - name: Lint with ruff
        run: uv run ruff check --diff
        continue-on-error: false

      # Type check with pyright
      - name: Type check with pyright
        run: uv run pyright

      # Tests with pytest
      - name: Test with pytest
        env:
          LOG_LEVEL: DEBUG
          AGENT__GEMINI_API_KEY: ${{ secrets.AGENT__GEMINI_API_KEY }}
          AGENT__OPENROUTER_API_KEY: ${{ secrets.AGENT__OPENROUTER_API_KEY }}
          ECOSYSTEM__FLARE_RPC_URL: "https://stylish-light-theorem.flare-mainnet.quiknode.pro/ext/bc/C/rpc"
          ECOSYSTEM__BLOCK_EXPLORER_URL: "https://flare-explorer.flare.network/api"
          VECTOR_DB__QDRANT_URL: "http://localhost:6333"
          VECTOR_DB__QDRANT_API_KEY: "your_secret_qdrant_api_key"
          GRAPH_DB__NEO4J_URI: ""
          GRAPH_DB__NEO4J_DATABASE: ""
          SOCIAL__X_API_KEY: "your_secret_twitter_key"
          SOCIAL__X_API_KEY_SECRET: "your_secret_twitter_key"
          SOCIAL__X_ACCESS_TOKEN: "your_secret_twitter_key"
          SOCIAL__X_ACCESS_TOKEN_SECRET: "your_secret_twitter_key"
          SOCIAL__TELEGRAM_API_TOKEN: "your_secret_telegram_token"
          TEE__SIMULATE_ATTESTATION_TOKEN: true
        run: uv run pytest -v
